server:
  port: 80
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      ##全局配置逻辑删除参数，不需要每个实体类单独设置
      logic-delete-field: isDeleted #全局逻辑删除字段名
      logic-not-delete-value: 0 #逻辑未删除值（默认0）
      logic-delete-value: 1 #逻辑已删除值（默认1）

reggie:
  path: F:\img\